name: Build solutions

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

defaults:
  run:
    working-directory: src/Nethermind

env:
  BUILD_CONFIG: release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Install dependencies
      run: |
        dotnet restore Benchmarks.sln
        dotnet restore Nethermind.sln
    - name: Build solutions
      run: |
        dotnet build Benchmarks.sln -c ${{ env.BUILD_CONFIG }} --no-restore
        dotnet build Nethermind.sln -c ${{ env.BUILD_CONFIG }} --no-restore
